---
title: "R Notebook"
output:
  pdf_document: default
  html_notebook: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Première partie: Simulations pour phi = 0

```{r}
rm(list = ls())
```

## Installation du package 
```{r}
devtools::install_github("aminaghoul/ARRW")
#devtools::install_github("gtromano/DeCAFS", force = TRUE)
```

## Chargement des packages
```{r, message=FALSE, warning = FALSE}
library(DeCAFS)
library(ARRW, quietly = TRUE)
# Pour ggplot2 et la manipulation des dataframes
library(tidyverse, quietly = TRUE)
# Pour tracer plusieurs graphiques en même temps
library(gridExtra, quietly = TRUE)

```



## Générer des valeurs de y avec DeCAFS

On prend comme paramètres :

```{r}
n <- 500
phi <- 0
sdEta <- 0.8
sdNu <- 1
```


```{r}
Y <- dataRWAR(n = n, poisParam = .01, meanGap = 15, phi = phi, sdEta = sdEta, sdNu = sdNu)
```

On trace le signal généré.

```{r}
signal <- data.frame(1:n,Y$signal)
colnames(signal) <- c("i", "mu")
ggplot(signal) + ggtitle("Signal généré par DeCAFS") + geom_point(aes(x = i ,y = mu))
```


```{r}
val <- def(sdEta = sdEta, sdNu = sdNu, phi = phi)
val
kis <- ki(val, n)
omega <- val$om
estim <- muhat(y = Y$y, kis = kis, omega)
```

```{r}
estimateur <- data.frame(1:n,estim)
colnames(estimateur) <- c("index", "muhat")
ggplot(estimateur) + ggtitle("Estimateur du signal") + geom_point(aes(x = index ,y = muhat))
```

## La variance de l'estimateur du signal

### Pour n = 10

```{r}
res <- var(val, sdEta, 10)
res
ggplot(res) + ggtitle("Variance de l'estimateur du modèle \n marche aléatoire plus bruit") + geom_point(aes(x = i, y = variance))
```


```{r}
res1 <- var1(val, sdEta, 10)
ggplot(res1) + ggtitle("Variance de l'estimateur du modèle marche aléatoire plus bruit") + geom_point(aes(x = i, y = variance))
```

### Pour n = 500

```{r}
res1 <- var1(val, sdEta, 450)
ggplot(res1) + ggtitle("Variance de l'estimateur du modèle marche aléatoire plus bruit") + geom_point(aes(x = i, y = variance))
```


## La fonction coût

```{r}
cost <- cost(y = Y$y, estim)
```

```{r}
cout <- data.frame(1:n, cost)
colnames(cout) <- c("index", "cout")
ggplot(cout) + ggtitle("Fonction de coût") + geom_point(aes(x = index , y = cout))
```



